### ISSUE TITLE
Xray router-request.log time_format is incorrect

### ISSUE THREAD

**Issue by danbarr** [jfrog/log-analytics#29]
This was fixed for Artifactory by PR #6 but the same issue exists for the Xray router-request.log timestamp.

The timestamp_format for the Xray router-request.log needs to be updated to match the actual log format.

Current value:
`time_format %Y-%m-%dT%H:%M:%SZ`

Correct value:
`time_format %Y-%m-%dT%H:%M:%S%:z`

**Comment by peters95** [comment]
looking into it thanks @danbarr

**Comment by peters95** [comment]
Fixed on https://github.com/jfrog/log-analytics/pull/31
