### ISSUE TITLE
Timestamps not reported to elasticsearch

### ISSUE THREAD

**Issue by SamBissig** [jfrog/log-analytics#58]
I had issues getting the reporting to elastic working properly. Issue is that timestamp values have not seen sent to elastic, the index did not contain a timestamp field. 

Versions used in my setup: 

- fluentd 1.11.5
- elastic: 7.10.0
- kibana: 7.10.0

We solved this issue as following:

Modified the OUT section and added additionally the two keys `include_timestamp true` and `time_key timestamp`.

```
<store>
      @type "elasticsearch"
      @id elasticsearch
      host "elasticsearch"
      port 9200
      user "elastic"
      password xxxxxx
      index_name "unified-artifactory"
      include_tag_key true
      time_key timestamp
      type_name "fluentd"
      include_timestamp true
      logstash_format false
  </store>
```

Additionally we had to modify the export.ndjson file and replace `timestamp` by `@timestamp`.

**Comment by peters95** [comment]
hi @SamBissig this issue has been addressed and closed in the relevant sub repo for Elastic.
